services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=airaclothinglabel@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  nextjs:
    image: ghcr.io/zyncc/aira:${GIT_COMMIT_HASH}
    environment:
      CLOUDINARY_API_KEY: /run/secrets/CLOUDINARY_API_KEY
      CLOUDINARY_API_SECRET: /run/secrets/CLOUDINARY_API_SECRET
      CLOUDINARY_CLOUD_NAME: /run/secrets/CLOUDINARY_CLOUD_NAME
      # SMTP_PASSWORD: /run/secrets/SMTP_PASSWORD
      DELHIVERY_TOKEN: /run/secrets/DELHIVERY_TOKEN
      # WHATSAPP_PHONE_NUMBER: /run/secrets/WHATSAPP_PHONE_NUMBER
      # WHATSAPP_CLOUD_API_KEY: /run/secrets/WHATSAPP_CLOUD_API_KEY
      DATABASE_URL: /run/secrets/DATABASE_URL
      DIRECT_URL: /run/secrets/DIRECT_URL
      # FACEBOOK_CLIENT_ID: /run/secrets/FACEBOOK_CLIENT_ID
      # FACEBOOK_CLIENT_SECRET: /run/secrets/FACEBOOK_CLIENT_SECRET
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: /run/secrets/NEXT_PUBLIC_GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: /run/secrets/GOOGLE_CLIENT_SECRET
      NEXT_PUBLIC_BASE_URL: /run/secrets/NEXT_PUBLIC_BASE_URL
      BETTER_AUTH_URL: /run/secrets/BETTER_AUTH_URL
      BETTER_AUTH_SECRET: /run/secrets/BETTER_AUTH_SECRET
      NEXT_PUBLIC_RAZORPAY_KEY_ID: /run/secrets/NEXT_PUBLIC_RAZORPAY_KEY_ID
      RAZORPAY_KEY_SECRET: /run/secrets/RAZORPAY_KEY_SECRET
      RAZORPAY_WEBHOOK_SECRET: /run/secrets/RAZORPAY_WEBHOOK_SECRET
      NODE_ENV: /run/secrets/NODE_ENV
    ports:
      - 3000:3000
    deploy:
      labels:
       - "traefik.enable=true"
       # Main domain
       - "traefik.http.routers.aira.rule=Host(`airaclothing.in`)"
       - "traefik.http.routers.aira.entrypoints=websecure"
       - "traefik.http.routers.aira.tls.certresolver=myresolver"
       - "traefik.http.services.aira.loadbalancer.server.port=3000"
       # Admin domain
      #  - "traefik.http.routers.aira-admin.rule=Host(`admin.airaclothing.in`)"
      #  - "traefik.http.routers.aira-admin.entrypoints=websecure"
      #  - "traefik.http.routers.aira-admin.tls.certresolver=myresolver"
      #  - "traefik.http.services.aira-admin.loadbalancer.server.port=3000"
      update_config:
        order: start-first
    secrets:
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - CLOUDINARY_CLOUD_NAME
      - DATABASE_URL
      - DIRECT_URL
      - GOOGLE_CLIENT_SECRET
      - NEXT_PUBLIC_RAZORPAY_KEY_ID
      - RAZORPAY_KEY_SECRET
      - RAZORPAY_WEBHOOK_SECRET
      # - SMTP_PASSWORD
      - DELHIVERY_TOKEN
      # - WHATSAPP_PHONE_NUMBER
      # - WHATSAPP_CLOUD_API_KEY
      # - FACEBOOK_CLIENT_ID
      # - FACEBOOK_CLIENT_SECRET
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID
      - NEXT_PUBLIC_BASE_URL
      - BETTER_AUTH_URL
      - BETTER_AUTH_SECRET
      - NODE_ENV

secrets:
  CLOUDINARY_API_KEY:
    external: true
  CLOUDINARY_API_SECRET:
    external: true
  CLOUDINARY_CLOUD_NAME:
    external: true
  DATABASE_URL:
    external: true
  DIRECT_URL:
    external: true
  GOOGLE_CLIENT_SECRET:
    external: true
  NEXT_PUBLIC_RAZORPAY_KEY_ID:
    external: true
  RAZORPAY_KEY_SECRET:
    external: true
  RAZORPAY_WEBHOOK_SECRET:
    external: true
  SMTP_PASSWORD:
    external: true
  DELHIVERY_TOKEN:
    external: true
  WHATSAPP_PHONE_NUMBER:
    external: true
  WHATSAPP_CLOUD_API_KEY:
    external: true
  FACEBOOK_CLIENT_ID:
    external: true
  FACEBOOK_CLIENT_SECRET:
    external: true
  NEXT_PUBLIC_GOOGLE_CLIENT_ID:
    external: true
  NEXT_PUBLIC_BASE_URL:
    external: true
  BETTER_AUTH_URL:
    external: true
  BETTER_AUTH_SECRET:
    external: true
  NODE_ENV:
    external: true

volumes:
  letsencrypt: