# 00-namespace-and-secret.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: aira-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: nextjs-env
  namespace: aira-prod
stringData:
  # Create this secret from your .env file by running:
  # kubectl create secret generic nextjs-env --from-env-file=.env -n aira-prod --dry-run=client -o yaml > 00-namespace-and-secret.yaml
  # Then, copy the key-value pairs under 'stringData' here.
  # For example:
  DATABASE_URL: "your-database-url"
  NEXTAUTH_SECRET: "your-nextauth-secret"
  # ... and so on for all variables in your .env file