# k8s/00b-traefik-rbac.yaml
# This file defines the necessary permissions (RBAC) for Traefik to work correctly.
# It allows Traefik to watch for IngressRoutes, Services, Endpoints, and Secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
      - middlewares
      - tlsoptions
      - traefikservices
      - ingressroutetcps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: default # Apply these permissions to the default service account...
    namespace: aira-prod # ...in your aira-prod namespace.
