# 03-ingress-route-fixed.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextjs-ingress
  namespace: aira
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # --- ACME HTTP-01 challenge route ---
    - match: PathPrefix(`/.well-known/acme-challenge/`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
    # --- Your Next.js app route ---
    - match: Host(`airaclothing.in`) || Host(`admin.airaclothing.in`)
      kind: Rule
      services:
        - name: nextjs-service
          port: 80
  tls:
    certResolver: myresolver
