apiVersion: apps/v1
kind: Deployment
metadata:
  name: aira-web
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: aira-web
          image: zyncc/aira:latest
          ports:
            - containerPort: 3000
