export const products = [
  {
    title: "Jordan Jumpman",
    description:
      "Slide in and go. Enjoy the cushioning of thick, lightweight foam for beach days or post-game hangouts.",
    price: 3195,
    images: [
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1725704452/Products/svvotloprmvlq9ojeeou.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1725704453/Products/fmkgic9jw1arfe1ulmwj.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1725704453/Products/ypwoiv76vsrrs1bimbzt.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1725704454/Products/iuwibscowvywtfh7gdwn.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1725704455/Products/ej0a32suhyvbirftz7d1.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1725704456/Products/rhglcxf1wctrrnbd1nro.jpg",
    ],
    category: "men",
    isArchived: false,
    isFeatured: true,
    color: "black",
    fabric: "Rubber",
    transparency: "Opaque",
    weavePattern: "Printed",
    fit: "Regular",
  },
  {
    title: "Shoes",
    description: "tgheosih",
    price: 9999,
    images: [
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305828/Products/ioskbiqihf07jogzwaza.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305828/Products/miknnoexzfusrnbvfhem.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305828/Products/n8wiudonzeetgcpud6ra.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305829/Products/pnanyc0lb5crnkodwfbe.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305828/Products/d4z6htevrts5vreerprj.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305828/Products/al5ti0crkxj5dvxnsj6r.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305829/Products/cxnvwc855wipcydynzxf.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1726305829/Products/ihtm5osfheybwgsulqtn.jpg",
    ],
    category: "men",
    isArchived: false,
    isFeatured: false,
    color: "black",
    fabric: "fswqr",
    transparency: "fqwrsfh",
    weavePattern: "gsa",
    fit: "afs",
    placeholderImages: [
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/ALGzrLi+t7a+tgDOzsiViYOaioYAyZ6bNAAApVZXAPbx8PTz8/39+9MaGEV/cIIyAAAAAElFTkSuQmCC",
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/ALO0sLO0sLCyrwDIwb3Iwb7U088AYElLIwAAyJ2YAPz+/vPy8v76+uEVGRj6u/NgAAAAAElFTkSuQmCC",
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/AL7EvL3Cu7W5sgCllpOtnZjW19EAq1ZYMwAAsZmYAPz7/Ojs7e3r7N1RGK3ynWQOAAAAAElFTkSuQmCC",
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/AMS/v6mXlsrFwwCEfX0bAACNg4MAyp6bcSMdzqWiAP/29P/Y0f/286LCFtkoMiLbAAAAAElFTkSuQmCC",
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/AKytqby+u7e5tQC9uLNOQD1nV1UAlHdzMwAAd0FAAOnp6ff29fj4+JqCFZEbGd6WAAAAAElFTkSuQmCC",
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/AKmqp7O2saeopQCAeXgzJyV6dnMArYqJNgAAq4eFAPz8/P79/f79/YrxFe3YG+hDAAAAAElFTkSuQmCC",
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMUlEQVR4nGP4/ft7aX5hZXo6w+njR3n5BNtsLRhik9MEGBg2erky7CxM+1GZ9m3FbABjJBEep9RLMwAAAABJRU5ErkJggg==",
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVR4nAEoANf/ADs1NGouK6aDfwBwAADRNjT0nZQASwAA1kNB/6CUACwAAPGmnf/79wxMEAlFLEFdAAAAAElFTkSuQmCC",
    ],
  },
  {
    title: "Air Jordan 9 G NRG",
    description:
      "Pay homage to the great history and heritage of the game in this special AJ9. The rustic wood-grain prints with warm vintage finishes nod to the sport's old-school long hitters that have that special smack off the tee, making for a happy life in any era. The metal-accented eyelets, lace tips and backtabs speak to the iconic, cutting-edge clubs that continue to set trends and smash through performance barriers.",
    price: 19695,
    images: [
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840301/gdmkeuovbp7rsahz271w.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840302/lbqpcfkg7mn0wq4uj83d.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840303/x5bwvokjvnp1leyufcoo.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840304/ujilorcbryioxyfymikl.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840305/nuecgjcquorrgsvrpniq.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840306/mniezsw1sgqdokc8casz.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840307/sqqnmxq0hl9vhdsev6tf.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840308/dxd1y4uzss5kv3trjzs2.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840309/x2uptyhaimdr7sfihenh.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840311/p3wecjqmsdjno4w81dgu.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840312/cp7xa2gtcnp6hsgmrpcn.jpg",
      "https://res.cloudinary.com/dfdusmp26/image/upload/v1715840313/c2omjfk0mlmreljv4oni.jpg",
    ],
    category: "men",
    isArchived: false,
    isFeatured: true,
    color: "brown",
    fabric: "Fabric",
    transparency: "Opaque",
    weavePattern: "Stitched",
    fit: "Regular",
  },
];
