name: Deploy Aira

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login in to Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u zyncc --password-stdin

      - name: Create ENV File
        run: |
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}" >> .env
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> .env
          echo "RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}" >> .env
      - name: Build Docker Image
        run: docker build -t ghcr.io/zyncc/aira:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/zyncc/aira:latest

  deploy:
    needs: build-and-push-docker-image
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/zyncc/ghcr.io/zyncc/aira:latest
            docker stop ghcr.io/zyncc/aira || true
            docker rm -f ghcr.io/zyncc/aira || true
            docker run -d -p 3000:3000 ghcr.io/zyncc/ghcr.io/zyncc/aira:latest
