name: Build and Deploy Aira to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            zyncc/aira:${{ github.sha }}
            zyncc/aira:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
            NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.27.3"

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Create or Update Kubernetes Secret
        run: |
          kubectl delete secret web-secrets --ignore-not-found

          kubectl create secret generic web-secrets \
            --from-literal=BETTER_AUTH_URL="${{ secrets.BETTER_AUTH_URL }}" \
            --from-literal=BETTER_AUTH_SECRET="${{ secrets.BETTER_AUTH_SECRET }}" \
            --from-literal=NEXT_PUBLIC_APP_URL="${{ secrets.NEXT_PUBLIC_APP_URL }}" \
            --from-literal=DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --from-literal=DELHIVERY_TOKEN="${{ secrets.DELHIVERY_TOKEN }}" \
            --from-literal=NEXT_PUBLIC_RAZORPAY_KEY_ID="${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }}" \
            --from-literal=RAZORPAY_KEY_SECRET="${{ secrets.RAZORPAY_KEY_SECRET }}" \
            --from-literal=RAZORPAY_WEBHOOK_SECRET="${{ secrets.RAZORPAY_WEBHOOK_SECRET }}" \
            --from-literal=TWITTER_CLIENT_ID="${{ secrets.TWITTER_CLIENT_ID }}" \
            --from-literal=TWITTER_CLIENT_SECRET="${{ secrets.TWITTER_CLIENT_SECRET }}" \
            --from-literal=WHATSAPP_PHONE_NUMBER="${{ secrets.WHATSAPP_PHONE_NUMBER }}" \
            --from-literal=WHATSAPP_CLOUD_API_KEY="${{ secrets.WHATSAPP_CLOUD_API_KEY }}" \
            --from-literal=NEXT_PUBLIC_GOOGLE_CLIENT_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" \
            --from-literal=GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            --from-literal=SMTP_HOST="${{ secrets.SMTP_HOST }}" \
            --from-literal=SMTP_PORT="${{ secrets.SMTP_PORT }}" \
            --from-literal=SMTP_USER="${{ secrets.SMTP_USER }}" \
            --from-literal=SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
            --from-literal=IMAGE_KIT_PUBLIC_API_KEY="${{ secrets.IMAGE_KIT_PUBLIC_API_KEY }}" \
            --from-literal=IMAGE_KIT_PRIVATE_API_KEY="${{ secrets.IMAGE_KIT_PRIVATE_API_KEY }}" \
            --from-literal=IMAGE_KIT_URL_ENDPOINT="${{ secrets.IMAGE_KIT_URL_ENDPOINT }}" \
            --from-literal=NODE_ENV="${{ secrets.NODE_ENV }}"

      - name: Update Kubernetes Manifests and Deploy
        run: |
          sed -i 's|zyncc/aira:latest|zyncc/aira:${{ github.sha }}|g' k8s/deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Trigger Rolling Deployment
        run: |
          kubectl set image deployment/web-deployment nextjs=zyncc/aira:${{ github.sha }}
