name: Build and Deploy Aira to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Encryption Key
        id: generate_key
        run: echo "key=$(openssl rand -hex 32)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            zyncc/aira:${{ github.sha }}
            zyncc/aira:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
            NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${{ steps.generate_key.outputs.key }}

      - name: Update image tag in deployment manifest
        run: |
          sed -i 's|image: zyncc/aira:IMAGE_TAG|image: zyncc/aira:${{ github.sha }}|' k8s/deployment.yaml

      - name: Create deployment directory on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: mkdir -p ~/app-deploy

      - name: Copy manifests to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "k8s/deployment.yaml,k8s/service.yaml"
          target: "~/app-deploy"

      - name: Deploy to K3s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Set KUBECONFIG for k3s
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

            # Ensure namespace exists
            kubectl create namespace web --dry-run=client -o yaml | kubectl apply -f -

            # Recreate the Kubernetes secret with all the new values
            kubectl delete secret generic app-secrets -n web --ignore-not-found
            kubectl create secret generic app-secrets -n web \
              --from-literal=IMAGE_KIT_PUBLIC_API_KEY='${{ secrets.IMAGE_KIT_PUBLIC_API_KEY }}' \
              --from-literal=IMAGE_KIT_PRIVATE_API_KEY='${{ secrets.IMAGE_KIT_PRIVATE_API_KEY }}' \
              --from-literal=IMAGE_KIT_URL_ENDPOINT='${{ secrets.IMAGE_KIT_URL_ENDPOINT }}' \
              --from-literal=SMTP_HOST='${{ secrets.SMTP_HOST }}' \
              --from-literal=SMTP_PORT='${{ secrets.SMTP_PORT }}' \
              --from-literal=SMTP_USER='${{ secrets.SMTP_USER }}' \
              --from-literal=SMTP_PASSWORD='${{ secrets.SMTP_PASSWORD }}' \
              --from-literal=DELHIVERY_TOKEN='${{ secrets.DELHIVERY_TOKEN }}' \
              --from-literal=WHATSAPP_PHONE_NUMBER='${{ secrets.WHATSAPP_PHONE_NUMBER }}' \
              --from-literal=WHATSAPP_CLOUD_API_KEY='${{ secrets.WHATSAPP_CLOUD_API_KEY }}' \
              --from-literal=DATABASE_URL='${{ secrets.DATABASE_URL }}' \
              --from-literal=TWITTER_CLIENT_ID='${{ secrets.TWITTER_CLIENT_ID }}' \
              --from-literal=TWITTER_CLIENT_SECRET='${{ secrets.TWITTER_CLIENT_SECRET }}' \
              --from-literal=GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}' \
              --from-literal=NEXT_PUBLIC_GOOGLE_CLIENT_ID='${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}' \
              --from-literal=NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
              --from-literal=BETTER_AUTH_SECRET='${{ secrets.BETTER_AUTH_SECRET }}' \
              --from-literal=BETTER_AUTH_URL='${{ secrets.BETTER_AUTH_URL }}' \
              --from-literal=NEXT_PUBLIC_RAZORPAY_KEY_ID='${{ secrets.NEXT_PUBLIC_RAZORPAY_KEY_ID }}' \
              --from-literal=RAZORPAY_KEY_SECRET='${{ secrets.RAZORPAY_KEY_SECRET }}' \
              --from-literal=RAZORPAY_WEBHOOK_SECRET='${{ secrets.RAZORPAY_WEBHOOK_SECRET }}' \
              --from-literal=NODE_ENV='${{ secrets.NODE_ENV }}'

            # Apply the Kubernetes manifests
            kubectl apply -f ~/app-deploy/deployment.yaml
            kubectl apply -f ~/app-deploy/service.yaml

            # Clean up the temporary directory
            rm -rf ~/app-deploy
